services:
  db:
    image: postgres:16
    container_name: fire_dispatch_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fire_dispatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fire_dispatch_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "5001:5001"
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - C:/Users/ASUS/Desktop/FYP/SimulStreaming/audio:/recordings:ro # to be edited
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  agents:
    build:
      context: .
      dockerfile: agents_service/Dockerfile
    container_name: fire_dispatch_agents
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
  dashboard:
    build:
      context: ./fire-dispatch-dashboard
      dockerfile: Dockerfile
    container_name: fire_dispatch_dashboard
    restart: unless-stopped
    environment:
      BACKEND_URL: http://api:8000
      BACKEND_API_URL: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:
